api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        multipart: ['multipart/form-data']
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    docs_formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_client_enabled: true
        pagination_items_per_page: 10
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false